project 'Smack.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smack' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smack
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON'
  pod 'Socket.IO-Client-Swift', :git => 'https://github.com/socketio/socket.io-client-swift'
end
